language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  # does not have headers provided, please ask https://launchpad.net/~pypy/+archive/ppa
  # maintainers to fix their pypy-dev package.
  - "pypy"
before_install: sudo apt-get install tree
# command to install dependencies
install:
  - pip install .
before_script: tree
# command to run tests
script: pulptest