language: python
matrix:
  include:
    # Ubuntu 14.04 LTS (Trusty Tahr)
    - dist: trusty
      python: 2.7
    - dist: trusty
      python: 3.4
    - dist: trusty
      python: pypy
    # Ubuntu 16.04 LTS (Xenial Xerus)
    - dist: xenial
      python: 3.5
    - dist: xenial
      python: pypy3.5
    # Ubuntu 18.04 LTS (Bionic Beaver)
    - dist: bionic
      python: 3.6
    - dist: bionic
      python: 3.7
    - dist: bionic
      python: 3.7-dev
    - dist: bionic
      python: 3.8-dev
    - dist: bionic
      python: nightly

before_install:
- sudo apt-get update -qq
- sudo apt-get install -qq glpk-utils

install:
- pip install .

script: pulptest

